name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "us-east-1" # Change to reflect your AWS Region

permissions:
  id-token: write  # Required for requesting the JWT
  contents: read   # Required for actions/checkout

jobs:
  InstallPythonAssumeIAMRole:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::794038212460:role/Rootedbysource-Role-9ztBCjFlEeep # Change to reflect your IAM role's ARN
          role-session-name: Rootedbysource-Role-9ztBCjFlEeep
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Cloud Custodian
        run: pip install c7n

      - name: Validate Cloud Custodian Policy
        run: custodian validate ./sample-policy.yml

      - name: Deploy Cloud Custodian Policy
        run: custodian run --region ${{ env.AWS_REGION }} --verbose ./sample-policy.yml -s ./out-log/
