policies:
  - name: s3-bucket-encryption-policy-absent
    resource: s3
    mode:
      type: periodic
      schedule: "rate(1 hour)"
      role: arn:aws:iam::794038212460:role/cloud-custodian-role-deploy-lambdas
      execution-options:
        assume_role: arn:aws:iam::794038212460:role/cloud-custodian-role-deploy-lambdas
        metrics: aws
    description: >
      Identifies S3 buckets without encryption policies and applies AES256 encryption,
      tagging remediated buckets.
    filters:
      - type: no-encryption-statement
    actions:
      - type: set-bucket-encryption
        crypto: AES256
        enabled: True
      - type: tag
        tag: secops
        value: remediated

  - name: s3-bucket-public-block-absent
    resource: s3
    mode:
      type: periodic
      schedule: "rate(1 hour)"
      role: arn:aws:iam::794038212460:role/cloud-custodian-role-deploy-lambdas
      execution-options:
        assume_role: arn:aws:iam::794038212460:role/cloud-custodian-role-s3-lambda
        metrics: aws
    description: >
      Identifies S3 buckets where public access is not blocked and remediates
      by enabling block settings, tagging remediated buckets.
    filters:
      - type: check-public-block
        BlockPublicAcls: true
        BlockPublicPolicy: true
    actions:
      - type: set-public-block
        BlockPublicAcls: true
        BlockPublicPolicy: true
      - type: tag
        tag: secops
        value: remediated
