name: Connect to an AWS role from a GitHub repository
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  
  AWS_REGION : "us-east-1" #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  InstallPythonAssumeIAMRole:
  runs-on: ubuntu-latest
  steps:
    - name: Git clone the repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::794038212460:role/Rootedbysource-Role-9ztBCjFlEeep  # change to reflect your IAM role’s ARN
        role-session-name: Rootedbysource-Role-9ztBCjFlEeep
        aws-region: us-east-1

    - name: Deploy Cloud Custodian Policy
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - run: pip install c7n

    - name: Validate Cloud Custodian Policy
      run: |
        custodian validate ./.github/workflows/sample-policy.yml

    - name: Run Cloud Custodian Policy
      run: |
        custodian run --region us-east-1 --verbose --output-dir ./out-log/ ./.github/workflows/sample-policy.yml
